apiVersion: v1
kind: Service
metadata:
  name: bifrost-gateway
  namespace: bifrost-apps
spec:
  type: LoadBalancer
  selector:
    app: bifrost-gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
