// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: events.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngress_SendEvent_FullMethodName       = "/bifrost.events.EventIngress/SendEvent"
	EventIngress_StreamBuildLogs_FullMethodName = "/bifrost.events.EventIngress/StreamBuildLogs"
)

// EventIngressClient is the client API for EventIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngressClient interface {
	SendEvent(ctx context.Context, in *PlatformEvent, opts ...grpc.CallOption) (*Ack, error)
	StreamBuildLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildLogLine, Ack], error)
}

type eventIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngressClient(cc grpc.ClientConnInterface) EventIngressClient {
	return &eventIngressClient{cc}
}

func (c *eventIngressClient) SendEvent(ctx context.Context, in *PlatformEvent, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, EventIngress_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngressClient) StreamBuildLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildLogLine, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngress_ServiceDesc.Streams[0], EventIngress_StreamBuildLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildLogLine, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngress_StreamBuildLogsClient = grpc.ClientStreamingClient[BuildLogLine, Ack]

// EventIngressServer is the server API for EventIngress service.
// All implementations must embed UnimplementedEventIngressServer
// for forward compatibility.
type EventIngressServer interface {
	SendEvent(context.Context, *PlatformEvent) (*Ack, error)
	StreamBuildLogs(grpc.ClientStreamingServer[BuildLogLine, Ack]) error
	mustEmbedUnimplementedEventIngressServer()
}

// UnimplementedEventIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngressServer struct{}

func (UnimplementedEventIngressServer) SendEvent(context.Context, *PlatformEvent) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventIngressServer) StreamBuildLogs(grpc.ClientStreamingServer[BuildLogLine, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamBuildLogs not implemented")
}
func (UnimplementedEventIngressServer) mustEmbedUnimplementedEventIngressServer() {}
func (UnimplementedEventIngressServer) testEmbeddedByValue()                      {}

// UnsafeEventIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngressServer will
// result in compilation errors.
type UnsafeEventIngressServer interface {
	mustEmbedUnimplementedEventIngressServer()
}

func RegisterEventIngressServer(s grpc.ServiceRegistrar, srv EventIngressServer) {
	// If the following call panics, it indicates UnimplementedEventIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngress_ServiceDesc, srv)
}

func _EventIngress_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngressServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngress_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngressServer).SendEvent(ctx, req.(*PlatformEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngress_StreamBuildLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngressServer).StreamBuildLogs(&grpc.GenericServerStream[BuildLogLine, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngress_StreamBuildLogsServer = grpc.ClientStreamingServer[BuildLogLine, Ack]

// EventIngress_ServiceDesc is the grpc.ServiceDesc for EventIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bifrost.events.EventIngress",
	HandlerType: (*EventIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventIngress_SendEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBuildLogs",
			Handler:       _EventIngress_StreamBuildLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "events.proto",
}
