// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DeployId      string                 `protobuf:"bytes,2,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformEvent) Reset() {
	*x = PlatformEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEvent) ProtoMessage() {}

func (x *PlatformEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEvent.ProtoReflect.Descriptor instead.
func (*PlatformEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PlatformEvent) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *PlatformEvent) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *PlatformEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *PlatformEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlatformEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlatformEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BuildLogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeployId      string                 `protobuf:"bytes,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLogLine) Reset() {
	*x = BuildLogLine{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogLine) ProtoMessage() {}

func (x *BuildLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogLine.ProtoReflect.Descriptor instead.
func (*BuildLogLine) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *BuildLogLine) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *BuildLogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *BuildLogLine) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x0ebifrost.events\"\xc2\x02\n" +
	"\rPlatformEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tdeploy_id\x18\x02 \x01(\tR\bdeployId\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12G\n" +
	"\bmetadata\x18\a \x03(\v2+.bifrost.events.PlatformEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\fBuildLogLine\x12\x1b\n" +
	"\tdeploy_id\x18\x01 \x01(\tR\bdeployId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x05\n" +
	"\x03Ack2\x97\x01\n" +
	"\fEventIngress\x12?\n" +
	"\tSendEvent\x12\x1d.bifrost.events.PlatformEvent\x1a\x13.bifrost.events.Ack\x12F\n" +
	"\x0fStreamBuildLogs\x12\x1c.bifrost.events.BuildLogLine\x1a\x13.bifrost.events.Ack(\x01B+Z)duolok/bifrost/gateway/internal/events/pbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_events_proto_goTypes = []any{
	(*PlatformEvent)(nil), // 0: bifrost.events.PlatformEvent
	(*BuildLogLine)(nil),  // 1: bifrost.events.BuildLogLine
	(*Ack)(nil),           // 2: bifrost.events.Ack
	nil,                   // 3: bifrost.events.PlatformEvent.MetadataEntry
}
var file_events_proto_depIdxs = []int32{
	3, // 0: bifrost.events.PlatformEvent.metadata:type_name -> bifrost.events.PlatformEvent.MetadataEntry
	0, // 1: bifrost.events.EventIngress.SendEvent:input_type -> bifrost.events.PlatformEvent
	1, // 2: bifrost.events.EventIngress.StreamBuildLogs:input_type -> bifrost.events.BuildLogLine
	2, // 3: bifrost.events.EventIngress.SendEvent:output_type -> bifrost.events.Ack
	2, // 4: bifrost.events.EventIngress.StreamBuildLogs:output_type -> bifrost.events.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
